name: build
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false

      - name: Install and Build 🔧
        env:
          PUBLIC_URL: /musicbox
          REACT_APP_APPLE_MUSIC_TOKEN: ${{ secrets.REACT_APP_APPLE_MUSIC_TOKEN }}
          REACT_APP_GOOGLE_API_KEY: ${{ secrets.REACT_APP_GOOGLE_API_KEY }}
          REACT_APP_GOOGLE_CLIENT_ID: ${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }}
          REACT_APP_GOOGLE_PROJECT_ID: ${{ secrets.REACT_APP_GOOGLE_PROJECT_ID }}
          REACT_APP_GOOGLE_AUTH_URI: ${{ secrets.REACT_APP_GOOGLE_AUTH_URI }}
          REACT_APP_GOOGLE_TOKEN_URI: ${{ secrets.REACT_APP_GOOGLE_TOKEN_URI }}
          REACT_APP_GOOGLE_AUTH_PROVIDER_X509_CERT_URL: ${{ secrets.REACT_APP_GOOGLE_AUTH_PROVIDER_X509_CERT_URL }}
          REACT_APP_GOOGLE_CLIENT_SECRET: ${{ secrets.REACT_APP_GOOGLE_CLIENT_SECRET }}
        run: |
          yarn
          yarn build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
